### ISSUE TITLE
启动copilot-activator出现问题，提示无法访问页面

### ISSUE THREAD

**Issue by binZai-ComeOn** [inu1255/copilot-activator#3]
![image](https://github.com/inu1255/copilot-activator/assets/56152943/ad1f3c76-15ec-465b-94de-9cee2ef503a2)

**Comment by inu1255** [comment]
有可能是网络问题，你看看背后窗口提示什么？

**Comment by binZai-ComeOn** [comment]
> 有可能是网络问题，你看看背后窗口提示什么？
我打开、关闭vpn再访问都是这样
![image](https://github.com/inu1255/copilot-activator/assets/56152943/ff6e86c0-099e-48da-ba5f-14cfa5542d9b)

**Comment by inu1255** [comment]
@binZai-ComeOn  淘宝上的请联系卖家哈，不要在这里提问
